import { Property, User, Inquiry } from './types';

// Mock Users
export const MOCK_USERS: User[] = [
  {
    id: 'user-1',
    name: 'Rajesh Sharma',
    email: 'rajesh.sharma@example.com',
    phone: '+91 98765 43210',
    role: 'user',
    registrationDate: '2024-01-15',
    bio: 'Property investor based in Civil Lines, Bareilly',
  },
  {
    id: 'user-2',
    name: 'Priya Gupta',
    email: 'priya.gupta@example.com',
    phone: '+91 87654 32109',
    role: 'user',
    registrationDate: '2024-01-20',
    bio: 'Looking for residential and commercial properties in Bareilly',
  },
  {
    id: 'user-3',
    name: 'Amit Verma',
    email: 'amit.verma@example.com',
    phone: '+91 76543 21098',
    role: 'user',
    registrationDate: '2024-02-01',
    bio: 'Startup founder seeking co-working spaces',
  },
  {
    id: 'user-4',
    name: 'Sunita Agarwal',
    email: 'sunita.agarwal@example.com',
    phone: '+91 65432 10987',
    role: 'user',
    registrationDate: '2024-02-05',
    bio: 'Real estate consultant in Bareilly region',
  },
  {
    id: 'admin-1',
    name: 'Admin Upfoxx',
    email: 'admin@upfoxxmedia.com',
    phone: '+91 75348 35937',
    role: 'admin',
    registrationDate: '2023-12-01',
    bio: 'Upfoxx Floors platform administrator',
  },
];

// Mock Properties
export const MOCK_PROPERTIES: Property[] = [
  {
    id: 'prop-1',
    title: 'Premium Office Space in Civil Lines',
    description: 'Modern furnished office space in the heart of Civil Lines, Bareilly. Ideal for IT companies,  consultancies, and professional firms. Features high-speed internet, power backup, and 24/7 security. Close to major banks and restaurants.',
    propertyType: 'office',
    listingType: 'rent',
    price: 35000,
    location: 'Civil Lines',
    city: 'Bareilly',
    state: 'Uttar Pradesh',
    zipcode: '243001',
    bedrooms: 0,
    bathrooms: 2,
    area: 1200,
    amenities: [
      { id: 'ac', name: 'AC' },
      { id: 'wifi', name: 'WiFi' },
      { id: 'parking', name: 'Parking' },
      { id: 'security', name: '24/7 Security' },
      { id: 'power-backup', name: 'Power Backup' },
      { id: 'cctv', name: 'CCTV' },
    ],
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&h=600&fit=crop',
    ],
    listingDate: '2024-02-15',
    viewCount: 1250,
    sellerId: 'user-1',
    status: 'approved',
    featured: true,
    ownerName: 'Rajesh Sharma',
    ownerPhone: '9876543210',
    ownerEmail: 'rajesh.sharma@example.com',
  },
  {
    id: 'prop-2',
    title: 'Co-Working Hub near Pilibhit Bypass',
    description: 'Vibrant co-working space with hot desks, dedicated desks, and private cabins. Starting from ₹999/month. Free WiFi, tea/coffee, electricity included. Perfect for freelancers, startups, and remote workers.',
    propertyType: 'co-working',
    listingType: 'rent',
    price: 999,
    location: 'Pilibhit Bypass',
    city: 'Bareilly',
    state: 'Uttar Pradesh',
    zipcode: '243006',
    bedrooms: 0,
    bathrooms: 3,
    area: 2500,
    amenities: [
      { id: 'wifi', name: 'WiFi' },
      { id: 'ac', name: 'AC' },
      { id: 'tea-coffee', name: 'Tea/Coffee' },
      { id: 'power-backup', name: 'Power Backup' },
      { id: 'parking', name: 'Parking' },
      { id: 'meeting-room', name: 'Meeting Room' },
    ],
    images: [
      'https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&h=600&fit=crop',
    ],
    listingDate: '2024-02-10',
    viewCount: 890,
    sellerId: 'user-3',
    status: 'approved',
    featured: true,
    ownerName: 'Amit Verma',
    ownerPhone: '7654321098',
    ownerEmail: 'amit.verma@example.com',
  },
  {
    id: 'prop-3',
    title: 'Professional Meeting Room – Hourly Booking',
    description: 'Fully equipped meeting room available for hourly bookings. Features projector, whiteboard, AC, and comfortable seating for up to 12 people. Ideal for client meetings, presentations, and team huddles.',
    propertyType: 'meeting-room',
    listingType: 'rent',
    price: 500,
    location: 'Civil Lines',
    city: 'Bareilly',
    state: 'Uttar Pradesh',
    zipcode: '243001',
    bedrooms: 0,
    bathrooms: 1,
    area: 400,
    amenities: [
      { id: 'projector', name: 'Projector' },
      { id: 'ac', name: 'AC' },
      { id: 'wifi', name: 'WiFi' },
      { id: 'tea-coffee', name: 'Tea/Coffee' },
    ],
    images: [
      'https://images.unsplash.com/photo-1582653291997-079a1c04e5a1?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1606761568499-6d2451b23c66?w=800&h=600&fit=crop',
    ],
    listingDate: '2024-02-20',
    viewCount: 540,
    sellerId: 'user-1',
    status: 'approved',
    featured: false,
    ownerName: 'Rajesh Sharma',
    ownerPhone: '9876543210',
    ownerEmail: 'rajesh.sharma@example.com',
  },
  {
    id: 'prop-4',
    title: 'Spacious 3BHK Flat in Rajendra Nagar',
    description: 'Beautiful 3-bedroom apartment in a well-maintained society in Rajendra Nagar. Features modular kitchen, balcony with garden view, dedicated parking, and 24/7 security. Close to schools and hospitals.',
    propertyType: 'apartment',
    listingType: 'rent',
    price: 18000,
    location: 'Rajendra Nagar',
    city: 'Bareilly',
    state: 'Uttar Pradesh',
    zipcode: '243122',
    bedrooms: 3,
    bathrooms: 2,
    area: 1400,
    amenities: [
      { id: 'kitchen', name: 'Modular Kitchen' },
      { id: 'balcony', name: 'Balcony' },
      { id: 'parking', name: 'Parking' },
      { id: 'security', name: '24/7 Security' },
      { id: 'power-backup', name: 'Power Backup' },
      { id: 'elevator', name: 'Elevator' },
    ],
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop',
    ],
    listingDate: '2024-02-12',
    viewCount: 2100,
    sellerId: 'user-2',
    status: 'approved',
    featured: true,
    ownerName: 'Priya Gupta',
    ownerPhone: '8765432109',
    ownerEmail: 'priya.gupta@example.com',
  },
  {
    id: 'prop-5',
    title: 'Commercial Shop in CB Ganj Market',
    description: 'Prime commercial shop located in the bustling CB Ganj market area. High footfall, excellent visibility, ground floor with shutter. Suitable for retail, showroom, or restaurant.',
    propertyType: 'commercial',
    listingType: 'rent',
    price: 45000,
    location: 'CB Ganj',
    city: 'Bareilly',
    state: 'Uttar Pradesh',
    zipcode: '243001',
    bedrooms: 0,
    bathrooms: 1,
    area: 800,
    amenities: [
      { id: 'parking', name: 'Parking' },
      { id: 'security', name: '24/7 Security' },
      { id: 'power-backup', name: 'Power Backup' },
    ],
    images: [
      'https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=800&h=600&fit=crop',
    ],
    listingDate: '2024-02-08',
    viewCount: 1680,
    sellerId: 'user-4',
    status: 'approved',
    featured: true,
    ownerName: 'Sunita Agarwal',
    ownerPhone: '6543210987',
    ownerEmail: 'sunita.agarwal@example.com',
  },
  {
    id: 'prop-6',
    title: 'Independent House for Sale in Subhash Nagar',
    description: 'Well-constructed 4-bedroom independent house with large garden and parking. East-facing property with Vastu compliance. Located in a quiet residential colony with good connectivity.',
    propertyType: 'house',
    listingType: 'sale',
    price: 7500000,
    location: 'Subhash Nagar',
    city: 'Bareilly',
    state: 'Uttar Pradesh',
    zipcode: '243005',
    bedrooms: 4,
    bathrooms: 3,
    area: 2200,
    amenities: [
      { id: 'garden', name: 'Garden' },
      { id: 'parking', name: 'Parking' },
      { id: 'kitchen', name: 'Modular Kitchen' },
      { id: 'power-backup', name: 'Power Backup' },
    ],
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop',
    ],
    listingDate: '2024-01-25',
    viewCount: 3200,
    sellerId: 'user-1',
    status: 'approved',
    featured: true,
    ownerName: 'Rajesh Sharma',
    ownerPhone: '9876543210',
    ownerEmail: 'rajesh.sharma@example.com',
  },
  {
    id: 'prop-7',
    title: 'Luxury Villa in Rampur Garden',
    description: 'Stunning 5-bedroom villa with private lawn, servant quarter, and modular kitchen. Marble flooring throughout, designer interiors, and car parking for 3 vehicles. Premium gated community.',
    propertyType: 'villa',
    listingType: 'sale',
    price: 15000000,
    location: 'Rampur Garden',
    city: 'Bareilly',
    state: 'Uttar Pradesh',
    zipcode: '243001',
    bedrooms: 5,
    bathrooms: 4,
    area: 3500,
    amenities: [
      { id: 'garden', name: 'Garden' },
      { id: 'parking', name: 'Parking' },
      { id: 'security', name: '24/7 Security' },
      { id: 'kitchen', name: 'Modular Kitchen' },
      { id: 'power-backup', name: 'Power Backup' },
      { id: 'cctv', name: 'CCTV' },
    ],
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop',
    ],
    listingDate: '2024-02-01',
    viewCount: 4500,
    sellerId: 'user-4',
    status: 'approved',
    featured: true,
    ownerName: 'Sunita Agarwal',
    ownerPhone: '6543210987',
    ownerEmail: 'sunita.agarwal@example.com',
  },
  {
    id: 'prop-8',
    title: '2BHK Flat near Izatnagar Station',
    description: 'Affordable 2-bedroom flat close to Izatnagar railway station. Well-ventilated rooms, attached bathrooms, and covered parking. Ideal for small families and working professionals.',
    propertyType: 'apartment',
    listingType: 'rent',
    price: 10000,
    location: 'Izatnagar',
    city: 'Bareilly',
    state: 'Uttar Pradesh',
    zipcode: '243122',
    bedrooms: 2,
    bathrooms: 2,
    area: 900,
    amenities: [
      { id: 'parking', name: 'Parking' },
      { id: 'power-backup', name: 'Power Backup' },
      { id: 'balcony', name: 'Balcony' },
    ],
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop',
    ],
    listingDate: '2024-02-18',
    viewCount: 780,
    sellerId: 'user-2',
    status: 'approved',
    featured: false,
    ownerName: 'Priya Gupta',
    ownerPhone: '8765432109',
    ownerEmail: 'priya.gupta@example.com',
  },
  {
    id: 'prop-9',
    title: 'Residential Plot in Deen Dayal Puram',
    description: 'Well-located residential plot with clear titles and all approvals. Wide road access, east-facing plot in a developing residential colony. Perfect for constructing your dream home.',
    propertyType: 'plot',
    listingType: 'sale',
    price: 3500000,
    location: 'Deen Dayal Puram',
    city: 'Bareilly',
    state: 'Uttar Pradesh',
    zipcode: '243001',
    bedrooms: 0,
    bathrooms: 0,
    area: 1800,
    amenities: [],
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&h=600&fit=crop',
    ],
    listingDate: '2024-02-05',
    viewCount: 1450,
    sellerId: 'user-1',
    status: 'approved',
    featured: false,
    ownerName: 'Rajesh Sharma',
    ownerPhone: '9876543210',
    ownerEmail: 'rajesh.sharma@example.com',
  },
  {
    id: 'prop-10',
    title: 'Furnished Office in Kotwali Area',
    description: 'Ready-to-move furnished office space near Kotwali. Includes workstations, AC, internet, and pantry. Suitable for law firms, CA offices, and consulting businesses.',
    propertyType: 'office',
    listingType: 'rent',
    price: 25000,
    location: 'Kotwali',
    city: 'Bareilly',
    state: 'Uttar Pradesh',
    zipcode: '243001',
    bedrooms: 0,
    bathrooms: 1,
    area: 700,
    amenities: [
      { id: 'ac', name: 'AC' },
      { id: 'wifi', name: 'WiFi' },
      { id: 'pantry', name: 'Pantry' },
      { id: 'parking', name: 'Parking' },
      { id: 'cctv', name: 'CCTV' },
    ],
    images: [
      'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&h=600&fit=crop',
    ],
    listingDate: '2024-02-22',
    viewCount: 620,
    sellerId: 'user-3',
    status: 'approved',
    featured: false,
    ownerName: 'Amit Verma',
    ownerPhone: '7654321098',
    ownerEmail: 'amit.verma@example.com',
  },
  {
    id: 'prop-11',
    title: 'Modern 3BHK in Satellite Township',
    description: 'Newly constructed 3-bedroom flat in Satellite Township with all modern amenities. Spacious rooms, Italian marble flooring, modular kitchen, and kids play area in the society.',
    propertyType: 'apartment',
    listingType: 'sale',
    price: 4800000,
    location: 'Satellite Township',
    city: 'Bareilly',
    state: 'Uttar Pradesh',
    zipcode: '243001',
    bedrooms: 3,
    bathrooms: 2,
    area: 1350,
    amenities: [
      { id: 'kitchen', name: 'Modular Kitchen' },
      { id: 'parking', name: 'Parking' },
      { id: 'elevator', name: 'Elevator' },
      { id: 'security', name: '24/7 Security' },
      { id: 'garden', name: 'Garden' },
      { id: 'gym', name: 'Gym' },
    ],
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop',
    ],
    listingDate: '2024-02-14',
    viewCount: 1890,
    sellerId: 'user-4',
    status: 'approved',
    featured: false,
    ownerName: 'Sunita Agarwal',
    ownerPhone: '6543210987',
    ownerEmail: 'sunita.agarwal@example.com',
  },
  {
    id: 'prop-12',
    title: 'Startup Office in Civil Lines',
    description: 'Perfect office for startups with 5-10 team members. Fully furnished with modern workstations, conference room access, and high-speed broadband. Walking distance from Civil Lines market.',
    propertyType: 'office',
    listingType: 'rent',
    price: 20000,
    location: 'Civil Lines',
    city: 'Bareilly',
    state: 'Uttar Pradesh',
    zipcode: '243001',
    bedrooms: 0,
    bathrooms: 1,
    area: 550,
    amenities: [
      { id: 'ac', name: 'AC' },
      { id: 'wifi', name: 'WiFi' },
      { id: 'parking', name: 'Parking' },
      { id: 'reception', name: 'Reception' },
      { id: 'tea-coffee', name: 'Tea/Coffee' },
    ],
    images: [
      'https://images.unsplash.com/photo-1556761175-4b46a572b786?w=800&h=600&fit=crop',
    ],
    listingDate: '2024-02-19',
    viewCount: 430,
    sellerId: 'user-3',
    status: 'pending',
    featured: false,
    ownerName: 'Amit Verma',
    ownerPhone: '7654321098',
    ownerEmail: 'amit.verma@example.com',
  },
];

// Mock Inquiries
export const MOCK_INQUIRIES: Inquiry[] = [
  {
    id: 'inq-1',
    propertyId: 'prop-1',
    buyerId: 'user-2',
    sellerEmail: 'rajesh.sharma@example.com',
    sellerPhone: '9876543210',
    buyerName: 'Priya Gupta',
    buyerEmail: 'priya.gupta@example.com',
    buyerPhone: '8765432109',
    message: 'I am interested in the office space in Civil Lines. Can I schedule a visit this week?',
    status: 'new',
    createdAt: '2024-02-16',
  },
  {
    id: 'inq-2',
    propertyId: 'prop-4',
    buyerId: 'user-3',
    sellerEmail: 'priya.gupta@example.com',
    sellerPhone: '8765432109',
    buyerName: 'Amit Verma',
    buyerEmail: 'amit.verma@example.com',
    buyerPhone: '7654321098',
    message: 'Is the 3BHK flat available for immediate move-in? Also, is the rent negotiable?',
    status: 'contacted',
    createdAt: '2024-02-13',
  },
  {
    id: 'inq-3',
    propertyId: 'prop-6',
    buyerId: 'user-2',
    sellerEmail: 'rajesh.sharma@example.com',
    sellerPhone: '9876543210',
    buyerName: 'Priya Gupta',
    buyerEmail: 'priya.gupta@example.com',
    buyerPhone: '8765432109',
    message: 'Very interested in this house. Can we discuss the pricing and loan options?',
    status: 'new',
    createdAt: '2024-02-20',
  },
  {
    id: 'inq-4',
    propertyId: 'prop-7',
    buyerId: 'user-3',
    sellerEmail: 'sunita.agarwal@example.com',
    sellerPhone: '6543210987',
    buyerName: 'Amit Verma',
    buyerEmail: 'amit.verma@example.com',
    buyerPhone: '7654321098',
    message: 'The Rampur Garden villa looks amazing. When can I visit and see the property?',
    status: 'new',
    createdAt: '2024-02-21',
  },
  {
    id: 'inq-5',
    propertyId: 'prop-2',
    buyerId: 'user-4',
    sellerEmail: 'amit.verma@example.com',
    sellerPhone: '7654321098',
    buyerName: 'Sunita Agarwal',
    buyerEmail: 'sunita.agarwal@example.com',
    buyerPhone: '6543210987',
    message: 'Looking for 3 dedicated desks for my team. What are the monthly plans available?',
    status: 'contacted',
    createdAt: '2024-02-19',
  },
];

// Helper function to get properties by seller ID
export const getPropertiesBySeller = (sellerId: string): Property[] => {
  return MOCK_PROPERTIES.filter((p) => p.sellerId === sellerId);
};

// Helper function to get inquiries by property ID
export const getInquiriesByProperty = (propertyId: string): Inquiry[] => {
  return MOCK_INQUIRIES.filter((i) => i.propertyId === propertyId);
};

// Helper function to get inquiries for seller's properties
export const getSellerInquiries = (sellerId: string): Inquiry[] => {
  const sellerPropertyIds = MOCK_PROPERTIES
    .filter((p) => p.sellerId === sellerId)
    .map((p) => p.id);
  return MOCK_INQUIRIES.filter((i) => sellerPropertyIds.includes(i.propertyId));
};

// Helper function to get user by ID
export const getUserById = (userId: string): User | undefined => {
  return MOCK_USERS.find((u) => u.id === userId);
};

// Helper function to get property by ID
export const getPropertyById = (propertyId: string): Property | undefined => {
  return MOCK_PROPERTIES.find((p) => p.id === propertyId);
};
